services:
  loot-factory-backend:
    build:
      context: ./LootFactory/web-app/backend
      dockerfile: Dockerfile
    container_name: dm-dashboard-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./LootFactory/data:/data:ro
    networks:
      dmdashboard-network:
        aliases:
          - backend
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  dmdashboard-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dmdashboard-frontend
    ports:
      - "3002:3002"
    depends_on:
      loot-factory-backend:
        condition: service_healthy
    networks:
      - dmdashboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  dmdashboard-network:
    driver: bridge 