version: '3.8'

services:
  backend:
    build:
      context: ./web-app/backend
      dockerfile: Dockerfile
    container_name: loot-factory-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./data:/app/data:ro
    networks:
      - loot-factory-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./web-app/frontend
      dockerfile: Dockerfile
    container_name: loot-factory-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - loot-factory-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  loot-factory-network:
    driver: bridge

volumes:
  loot-data:
    driver: local 