# Development overrides for docker-compose.yml
services:
  backend:
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./web-app/backend:/app
      - ./data:/app/data:ro
    command: npm run dev
    ports:
      - "3001:3001"

  frontend:
    environment:
      - NODE_ENV=development
    build:
      context: ./web-app/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./web-app/frontend:/app
    command: npm run dev 